/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CursosRouteImport } from './routes/cursos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CursosNarrativasVisualesRouteImport } from './routes/cursos.narrativas-visuales'

const CursosRoute = CursosRouteImport.update({
  id: '/cursos',
  path: '/cursos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosNarrativasVisualesRoute =
  CursosNarrativasVisualesRouteImport.update({
    id: '/narrativas-visuales',
    path: '/narrativas-visuales',
    getParentRoute: () => CursosRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cursos': typeof CursosRouteWithChildren
  '/cursos/narrativas-visuales': typeof CursosNarrativasVisualesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cursos': typeof CursosRouteWithChildren
  '/cursos/narrativas-visuales': typeof CursosNarrativasVisualesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cursos': typeof CursosRouteWithChildren
  '/cursos/narrativas-visuales': typeof CursosNarrativasVisualesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cursos' | '/cursos/narrativas-visuales'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cursos' | '/cursos/narrativas-visuales'
  id: '__root__' | '/' | '/cursos' | '/cursos/narrativas-visuales'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CursosRoute: typeof CursosRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/cursos': {
      id: '/cursos'
      path: '/cursos'
      fullPath: '/cursos'
      preLoaderRoute: typeof CursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos/narrativas-visuales': {
      id: '/cursos/narrativas-visuales'
      path: '/narrativas-visuales'
      fullPath: '/cursos/narrativas-visuales'
      preLoaderRoute: typeof CursosNarrativasVisualesRouteImport
      parentRoute: typeof CursosRoute
    }
  }
}

interface CursosRouteChildren {
  CursosNarrativasVisualesRoute: typeof CursosNarrativasVisualesRoute
}

const CursosRouteChildren: CursosRouteChildren = {
  CursosNarrativasVisualesRoute: CursosNarrativasVisualesRoute,
}

const CursosRouteWithChildren =
  CursosRoute._addFileChildren(CursosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CursosRoute: CursosRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
